package use_case.asset_and_liability_apply_rate;

public interface AssetAndLiabilityApplyRateOutputBoundary {
    void prepareAssetAndLiabilitySuccessView (AssetAndLiabilityApplyRateOutputData assetAndLiabilityApplyRateOutputData);
}
